version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
